### ISSUE TITLE
Include details of installing Conda

### ISSUE THREAD

**Issue by ns-rse** [RSE-Sheffield/conda-environments-for-effective-and-reproducible-research#12]
Realised that the course material assumes Conda is already installed on a users system.

This many not always be the case!

We should add to Episode 1 details of how to install [mini]conda, at the bare minimum linking to and copying the basic instructions.

However, this may perhaps be a pre-requisite "Setup" requirement and could be added as an appendix and linked to in the setup material/emails.

**Comment by bobturneruk** [comment]
Is this not sufficient? https://rse.shef.ac.uk/introduction-to-conda-for-data-scientists/setup/

**Comment by ns-rse** [comment]
It is more than sufficient, I just didn't clock it and when looking at the table on the front page thought it was a column header.
