### ISSUE TITLE
Teach how to update conda before installing any packages

### ISSUE THREAD

**Issue by EdwinB12** [RSE-Sheffield/conda-environments-for-effective-and-reproducible-research#21]
To ensure the demonstrator and all users have the same packages available, the entire class should update conda together: 
`
conda update conda `

**Comment by ns-rse** [comment]
According to the [documentation](https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#auto-update-conda) by default Conda automatically updates itself... "_conda updates itself any time a user updates or installs a package in the root environment._" . Would have to make the distinction of running `conda update conda` under `base` and any other created and activated environment.

**Comment by ns-rse** [comment]
Conda automatically updates (see above comment) so don't feel the need to explicitly call this out.
