### ISSUE TITLE
Would an example be useful for explaining the motivation behind environments? 

### ISSUE THREAD

**Issue by EdwinB12** [RSE-Sheffield/conda-environments-for-effective-and-reproducible-research#23]
The first page is quite text heavy and although I think its useful to have that content as notes, do we think an example would be useful to demonstrate the perks behind using an virtual environment tool such as conda? 

Or rather than an example, maybe a schematic? Could be as simple as the first picture in this article? 

https://www.dataquest.io/blog/a-complete-guide-to-python-virtual-environments/

**Comment by ns-rse** [comment]
Closed by #27
