### ISSUE TITLE
Previewing changes made on branch

### ISSUE THREAD

**Issue by EdwinB12** [RSE-Sheffield/conda-environments-for-effective-and-reproducible-research#29]
@bobturneruk @ns-rse - How do you preview changes made on a new branch? Do you build a local version of the website? And if so, is there any documentation for how to do this?

**Comment by bobturneruk** [comment]
https://carpentries.github.io/lesson-example/setup.html#jekyll-setup-for-lesson-development

**Comment by EdwinB12** [comment]
Thanks!
